"""Add ON DELETE CASCADE to Favorite table

Revision ID: 4c74dab3d4d6
Revises: c8b55937cc01
Create Date: 2024-12-26 00:33:09.220203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c74dab3d4d6'
down_revision: Union[str, None] = 'c8b55937cc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_favorite_item_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'item', ['favorite_item'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_favorite_item_fkey', 'favorite', 'item', ['favorite_item'], ['id'])
    # ### end Alembic commands ###
