"""timestamp in search history edit

Revision ID: a699b0ad9108
Revises: 4c74dab3d4d6
Create Date: 2024-12-26 19:03:20.463952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a699b0ad9108'
down_revision: Union[str, None] = '4c74dab3d4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('search_history', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('search_history', 'time')
    # ### end Alembic commands ###
