"""email and time added

Revision ID: c8b55937cc01
Revises: 6cb7b7331f91
Create Date: 2024-12-05 20:55:50.060828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b55937cc01'
down_revision: Union[str, None] = '6cb7b7331f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('contract', 'timestamp')
    # ### end Alembic commands ###
