services:
  web_app:
    build: .
    command: python app.py
    ports:
      - "5001:5001"
    environment:
      - RABBIT_HOST=rabbit_mq
      - DB_HOST=db_host
      - DB_USER=postgres
      - DB_PASSWORD=example


  rabbit_mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"


  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      - RABBIT_HOST=rabbit_mq
      - DB_HOST=db_host
      - DB_USER=postgres
      - DB_PASSWORD=example
    depends_on:
      - rabbit_mq
      - db_postgres

  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    hostname: db_host
    ports:
      - '5432:5432'